export enum UserActionTypes {
    GET_USERS_REQUEST = 'GET_USERS_REQUEST',
    GET_USERS_SUCCESS = 'GET_USERS_SUCCESS',
    CREATE_USERS_REQUEST = 'CREATE_USERS_REQUEST',
    DELETE_USERS_REQUEST = 'DELETE_USERS_REQUEST'
}